apiVersion: v1
kind: ConfigMap
metadata:
  name: webapp-config
data:
  APP_ENV: "development"
  LOG_LEVEL: "debug"
  FEATURE_FLAG: "enabled"
EOF
 
# Update dev kustomization
cat > overlays/dev/kustomization.yaml << 'EOF'
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
 
namespace: dev
namePrefix: dev-
 
bases:
  - ../../base
 
patchesStrategicMerge:
  - replica-patch.yaml
  - configmap-patch.yaml
 
commonLabels:
  environment: dev
